### ISSUE TITLE
ROADToken Nonce

### ISSUE THREAD

**Issue by FrankSpierings** [dirkjanm/ROADtools#14]
Could you please push the code that acquires the nonce, as described in your Twitter; https://twitter.com/_dirkjan/status/1312095317614047232 and your blog https://dirkjanm.io/abusing-azure-ad-sso-with-the-primary-refresh-token/ ?

**Comment by dirkjanm** [comment]
The nonce code is part of roadlib (the python part), which was uploaded to PyPi yesterday. For ROADtoken, you can get that here: https://github.com/dirkjanm/ROADtoken

**Comment by FrankSpierings** [comment]
Okay thank you, nevermind my stupidity in that case :)
