### ISSUE TITLE
Runtime Error faced while gathering data

### ISSUE THREAD

**Issue by CuriosoCat** [dirkjanm/ROADtools#15]
Hello,

I've tried running the "gather" command twice, but I'm still facing a runtime error and as a result the data seems to be incomplete.

![image](https://user-images.githubusercontent.com/46101882/95298414-a164c680-08ae-11eb-91fa-ad254b42aaab.png)

Any idea what might be causing this?

Any help would be greatly appreciated!

**Comment by dirkjanm** [comment]
data gathering is actually completed with success, but there seems to be some cleanup going wrong. I'll look if there is something I can do to fix this, but in the meanwhile you can ignore this error, the gathering is already done and you should be able to use it without issue :)

**Comment by CuriosoCat** [comment]
I see, thanks for clarifying and taking the time to get back to this issue!

Awesome tool by the way 👍
