### ISSUE TITLE
from sqlalchemy import Binary issue (on Windows)

### ISSUE THREAD

**Issue by tijldeneut** [dirkjanm/ROADtools#19]
Should Binary be BINARY on line 5 of the following file?
`roadlib/roadtools/roadlib/metadef/database.py`

Tested on Python3.9.1 x64 on Win10 2004 with the Visual Studio tools installed and after compiling via
`git clone https://github.com/dirkjanm/ROADtools`
`python3 setup.py install`

Trying to confirm it now on Win10 20H2

FYI: love your work and blogs !

**Comment by dirkjanm** [comment]
I don't think so, and I haven't seen anyone else with this issue. Unless someone else runs into this, i'm closing this as false positive

**Comment by dirkjanm** [comment]
Actually it seems that on Windows there are newer versions of sqlalchemy that don't have the Binary definition. This issue should be fixed now.
