### ISSUE TITLE
Feature: Ability to resume gather phase when roadtools is interrupted

### ISSUE THREAD

**Issue by SoloDefend** [dirkjanm/ROADtools#20]
It would be pretty awesome if we could have a way to resume the gather phase when the connection is interrupted (internet drops, system crashes etc.). 

I was just doing a pull against a MASSIVE Tenant (roadtools gather running for 4.5 days) and had a system crash. All of that work halted, with only a portion of the results in the database.

**Comment by dirkjanm** [comment]
I agree it'd be a nice feature. Maybe at some point I'll find a way to do this, but it's quite hard to reliably know what data is and is not gathered during a run that is optimized to run as efficient as possible. On a positive note, I've included some improvements that should speed up stage 2 gathering in the latest version.

**Comment by dirkjanm** [comment]
You can now skip the first phase of data gathering if that already has been completed with `--skip-first-phase` and it will skip right to the second phase :)
