### ISSUE TITLE
Unable to download  files from the Azure Pipelines artifacts

### ISSUE THREAD

**Issue by stevenkennyit** [dirkjanm/ROADtools#25]
Unable to download the roadlib and roadrecon zip files from Azure Pipelines. I can see the "ROADTools" published artifact but no download option. 

Here's the URL: https://dev.azure.com/dirkjanm/ROADtools/_build/results?buildId=477&view=artifacts&pathAsName=false&type=publishedArtifacts
And here's a screenshot of the page:
![roadtools_unable_download](https://user-images.githubusercontent.com/22411246/108600974-00286980-7392-11eb-85fc-90defe49e594.PNG)

Apologies if I've missed something obvious. Thanks

**Comment by dirkjanm** [comment]
On my screen there's a options button with a download link which points to https://dev.azure.com/dirkjanm/44ad50c7-c429-4472-8a02-c113bf42a956/_apis/build/builds/477/artifacts?artifactName=ROADtools&api-version=6.0&%24format=zip

The options button only appears when you hover the archive name with the mouse. I agree it's not quite an intuitive interface.

**Comment by stevenkennyit** [comment]
Awesome. Thanks Dirk. I'm able to download the files now.
