### ISSUE TITLE
404 error when using Gather

### ISSUE THREAD

**Issue by sm00v** [dirkjanm/ROADtools#30]
I continually have this 404 error when running the gather module. This results in broken data displaying in bloodhound as well as the GUI. Nothing actually displays in either although you can tell data was imported. Any ideas?

Macbook-Pro:ldap user$ roadrecon gather
Starting data gathering phase 1 of 2 (collecting objects)
Gathered 1440 groups, switching to 3-phase approach for efficiency
Starting data gathering phase 2 of 3 (collecting properties and relationships)
Error 404 for URL https://graph.windows.net/e40ghd9b-e1f4-4b3c-8532-e09c64944488/roleAssignments?api-version=1.61-internal&$filter=roleDefinitionId eq 'a0b1b346-2i3k-4e8b-98f8-7539k20e4970'
{"odata.error":{"code":"Request_ResourceNotFound","message":{"lang":"en","value":"Resource 'a0b1b346-2i3k-4e8b-98f8-7539k20e4970' does not exist or one of its queried reference-property objects are not present."},"requestId":"17e7ede0-2222-4102-8ddd-3k8df013d2fe","date":"2021-06-02T00:47:42"}}
Starting data gathering phase 3 of 3 (collecting group memberships and device owners)
Refreshed token
ROADrecon gather executed in 493.92 seconds and issued 5185 HTTP requests.

**Comment by dirkjanm** [comment]
The 404 happens sometimes, I'm not sure why, but it should not matter for the overall process. If you don't have any data in the GUI that is likely due to something else (it seems to have gathered quite some data though). Does roadrecon gui give you any errors? (Either on the command line or in the browser console)

**Comment by sm00v** [comment]
> The 404 happens sometimes, I'm not sure why, but it should not matter for the overall process. If you don't have any data in the GUI that is likely due to something else (it seems to have gathered quite some data though). Does roadrecon gui give you any errors? (Either on the command line or in the browser console)
<img width="1228" alt="Screen Shot 2021-06-08 at 9 29 08 AM" src="https://user-images.githubusercontent.com/34954477/121215793-8d0e0a80-c83d-11eb-903a-bdf64385c2bc.png">

0 errors. Here is a screenshot from the roadrecon gui.

**Comment by dirkjanm** [comment]
I also see the logo not loading so this is likely a local issue. Do you see any errors in your browser console or do you have any plugins active that could block resources from loading?
Maybe try a different browser?
