### ISSUE TITLE
Error while gathering data

### ISSUE THREAD

**Issue by debifrank** [dirkjanm/ROADtools#4]
Hello, I attempted to use your tool in an engagement about a week ago and ran into an issue while attempting to gather data. The authentication process worked without issue and generated the token/key file correctly. I don't have access to the environment anymore but do have a couple of snippets that may be helpful:

`
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1175, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 808, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/sqltypes.py", line 913, in process
    return DBAPIBinary(value)
TypeError: memoryview: a bytes-like object is required, not 'str'
`

Maybe more helpful:

`
sqlalchemy.exc.StatementError: (builtins.TypeError) memoryview: a bytes-like object is required, not 'str'
[SQL: INSERT INTO "TenantDetails" ("objectType", "objectId", "deletionTimestamp", "assignedPlans", "authorizedServiceInstance", city, "cloudRtcUserPolicies", "companyLastDirSyncTime", "companyTags", "compassEnabled", country, "countryLetterCode", "dirSyncEnabled", "displayName", "isMultipleDataLocationsForServicesEnabled", "marketingNotificationEmails", "postalCode", "preferredLanguage", "privacyProfile", "provisionedPlans", "provisioningErrors", "releaseTrack", "replicationScope", "securityComplianceNotificationMails", "securityComplianceNotificationPhones", "selfServePasswordResetPolicy", state, street, "technicalNotificationMails", "telephoneNumber", "tenantType", "verifiedDomains", "windowsCredentialsEncryptionCertificate") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'odata.type': 'Microsoft.DirectoryServices.TenantDetail', 'objectType': 'Company', 'objectId': 'bbab6148-da32-4d6a-a330-5231314f3e75', 'deletionTime ... (13234 characters truncated) ... EXr65uJ+WtPvpp8VvFs1OEXzKu7SEeIkhtUR2Bo9dTL+7KMKhd5JdXiVlGNX/3b3jAmz6c4PG4jhoKoK/q0Thlpx7gmOvHYfqnD6iEgH356bqSUCvAk0aRn5RRnj2IOOfsNDE8stHIuUz/P6uyg'}]]
`

**Comment by dirkjanm** [comment]
Thanks, it appears that the database (rightfully) expects a binary value but instead the Azure AD graph gives us base64 encoded binary as a string, which breaks things. Will look in how to best fix this.

**Comment by dirkjanm** [comment]
Pushed a hotfix for this to master, if you are in a position to retest this at some point let me know!

**Comment by dirkjanm** [comment]
Closing this, if there is new info or this is not yet fixed feel free to reopen.
