### ISSUE TITLE
403

### ISSUE THREAD

**Issue by xdxiaoran** [dirkjanm/ROADtools#43]
when I started gather information，all URLs seems 403 error like
Error 403 for URL https://graph.windows.net/xxxxxx/xxxxxxx?api-version=1.61-internal
could  you tell me the possible reason？

**Comment by dirkjanm** [comment]
it is possible they blocked enumeration as described here: https://dirteam.com/sander/2019/06/11/howto-disable-account-enumeration-in-azure-active-directory/
this is also expected behaviour if you are using a guest account and enumerating users/groups is disabled for guests
