### ISSUE TITLE
[bug] Some users missing

### ISSUE THREAD

**Issue by quentinhardy** [dirkjanm/ROADtools#44]
Hello,

Thank you for this very useful tool.

I collected a big database (1,2GB) containing more than 80k users, many groups, etc.
Some users are skipped during the dump step. I don't know why because I don't remember errors in Roadrecon outpout.
I have not checked groups or devices. Perhaps the same problem.

I have tested through the web interface and the python API:
```python
[...]
session = database.get_session(database.init())
for user in session.query(User):
[...]
```

If I use _MicroBurst_ or _Get-MsolUser_ (MSOnline), these missing users are collected.

Best regards,

**Comment by dirkjanm** [comment]
There have been some minor changes that could have caused this issue which are now resolved. In any case its very hard for me to debug this unless there is some reproducible case that we could drill into. So I'm closing this as it's not something I think I can debug or reproduce.
