### ISSUE TITLE
Empty strongAuthenticationDetail - How to get MFA status of each user

### ISSUE THREAD

**Issue by quentinhardy** [dirkjanm/ROADtools#45]
Hello,

All my AAD users have this following configuration in my _roadrecon_ database:

```
strongAuthenticationDetail => {'encryptedPinHash': None, 'encryptedPinHashHistory': None, 'methods': [], 'oathTokenMetadata': [], 'requirements': [], 'phoneAppDetails': [], 'proofupTime': None, 'verificationDetail': None}
```
If I have well understood, the _strongAuthenticationDetail_ key should give information about the MFA status for a user.

Why all my users have an "empty" _strongAuthenticationDetail_ while some of them have MFA enable?  Is it a privilege problem of the AAD user which has been used for running Roadrecon ? This user was the "Gloabl reader" role.

How I can get the MFA status of each AAD user through Roadtools ?

Thank you in advance,

**Comment by dirkjanm** [comment]
In my testing this still works with the correct privileges (Global reader/Admin). If you're sure you gathered the information with the correct privileges, then i'm not sure what the issue could be here.
You could try running the tool with `--mfa` explicitly to see if that does gather the MFA information.

**Comment by dirkjanm** [comment]
It appears that in larger tenants the `--mfa` switch is needed to collect this even with the correct privileges. In small tenants it collects it without that flag as well.
