### ISSUE TITLE
Error on "gather" module

### ISSUE THREAD

**Issue by kapshure** [dirkjanm/ROADtools#5]
Hi, I've ran across an issue on multiple clients (ubuntu 18.04, kali 2020.2), that I'm just not experienced enough to fix it seems, pardon the inexperience:

- i did a "pip3 install roadrecon" & everything seems to look good
- i do a "roadrecon auth" and I'm able to authenticate and get a token
- i go to do "roadrecon gather -f [TOKEN]" & I get this error:
"File "/usr/local/lib/python3.6/dist-packages/roadtools/roadrecon/gather.py", line 416, in main
    asyncio.run(run(args, dburl))
AttributeError: module 'asyncio' has no attribute 'run'"
- i went and rechecked that 'asyncio' is installed (asyncio-3.4.3)
I'm just not versed enough in python, despite trying to unravel this over the weekend

Comical enough, my Win10 WSL environment had no issues getting the entire process to run :)

any ideas, just for my own edification? I'm sure its PEBKAT

**Comment by dirkjanm** [comment]
Actually it seems roadrecon gather requires python 3.7. I'll see if I can fix this specific piece for 3.6 as well.
