### ISSUE TITLE
roadtx prtenrich crashes with AttributeError

### ISSUE THREAD

**Issue by dadevel** [dirkjanm/ROADtools#51]
I got an error with `roadtx prtenrich` after successful MFA:

~~~
❯ roadtx prtenrich
Traceback (most recent call last):
  File "/home/daniel/.local/bin/roadtx", line 8, in <module>
    sys.exit(main())
  File "/home/daniel/.local/pipx/venvs/roadtx/lib/python3.10/site-packages/roadtools/roadtx/main.py", line 629, in main
    if args.ngcmfa_drs_auth:
AttributeError: 'Namespace' object has no attribute 'ngcmfa_drs_auth'
~~~

This is happens because `args.ngcmfa_drs_auth` is accessed but never assigned.
The accompanying `add_argument()` call is commented out in line 370.

After commenting out line 629 to 633 `prtenrich` worked as intended.

By the way, thanks for your nice work!

**Comment by dirkjanm** [comment]
thanks, fixed it now :)
