### ISSUE TITLE
Feature request:  "signinaudience" on App Registrations

### ISSUE THREAD

**Issue by nerdyninny** [dirkjanm/ROADtools#59]
Related to this issue:
https://www.wiz.io/blog/azure-active-directory-bing-misconfiguration

**Comment by dirkjanm** [comment]
The property "availableToOtherTenants" is already available in the app overview (shown as "multitenant" in the applications table), I think this represents the same information although it does not distinguish between which accounts are accepted aside from the application being multi-tenant enabled.

**Comment by dirkjanm** [comment]
closing due to lack of feedback on what information is missing or could be added
