### ISSUE TITLE
Feature request: Add "--no-workers" option

### ISSUE THREAD

**Issue by Warlord711** [dirkjanm/ROADtools#74]
I just came along an Azure AD where the 3-phase approach ran into a deadlock situation.

My workaround was to increase the MAX_GROUP value within the gather.py to be greater than the current group number in the tenant.

Can you add a simple --no-workers option to the gather phase/function to allow an override ?

**Comment by dirkjanm** [comment]
Hey, while that is an option, I'd be more interested in finding the root cause of that deadlock and what caused that (sounds like something I'd like to fix). Do you have any more context on where it got stuck or what error it threw when you stopped the gathering process?

**Comment by Warlord711** [comment]
![freeze](https://github.com/dirkjanm/ROADtools/assets/13434129/b569be6d-6d69-4dd0-b856-31e33891162a)

roadrecon freezes at this point and you can wait forever. If you `tail -f` the roadrecon.db you can see that no info is processed.

When CTRL+C out of it, I get a bunch of

`[sqlalchemy.exc.InvalidRequestError: A transaction is already begun on this Session.]` 
errors in the output.

**Comment by dirkjanm** [comment]
Ah thanks, that helps, I'm going to debug this some more, probably the result of a recent migration to newer sqlalchemy version that I need to test a bit better.
