### ISSUE TITLE
Keep open option doesn't keep the browser open

### ISSUE THREAD

**Issue by realspookysocks** [dirkjanm/ROADtools#78]
It seems that using the -k option doesn't keep the browser open for longer than about a minute.

For instance...
`roadtx browserprtauth -d ./geckodriver -k -url https://outlook.office.com --prt MC5[snip] --prt-sessionkey 2e[snip]`
will close out after about a minute.

To fix this, in the file /roadtools/roadtx/roadtools/roadtx/selenium.py, I added this code to the end of the selenium_login function before the last return (return False), at line 210:
```
if keep:
    time.sleep(1800)
```
I also had to `import time` at the top of that file. If I were cooler/had more time, I would have made it a variable and checked the other places this needed to go.

Also, if I didn't specify the redirect url, I believe it still closed out the browser even with my addition.

**Comment by dirkjanm** [comment]
hey, thanks for the feedback, I have added some improvements to the latest version which should keep the browser window open as expected
