### ISSUE TITLE
Proxy option enhancement

### ISSUE THREAD

**Issue by realspookysocks** [dirkjanm/ROADtools#79]
The proxy option currently expects an http/https proxy. In practice, I've found what I need is a socks proxy so I can tunnel my connection through an environment to get around conditional access policies.

To do that, I changed lines 62 and 63 in file `/roadtools/roadtx/roadtools/roadtx/selenium.py` to...
```
'http': f'socks5://{self.proxy}',
'https': f'socks5://{self.proxy}',
```

**Comment by dirkjanm** [comment]
this is now supported in the latest version on git
