### ISSUE TITLE
If ROAD tools can get context and derivedkey?

### ISSUE THREAD

**Issue by ql3xHd630** [dirkjanm/ROADtools#84]
I Notice that there is method "Pass the Certificate" to move to other computer in AzureAD joined local AD.
this tech need context and derivedkey from mimikatz. But mimikatz need a administrator permission to get these information.

**Comment by dirkjanm** [comment]
Do you have a reference of where that is required? ROADtools can create a context + derived key combination from a PRT, but it cannot do that from data on an endpoint directly.

**Comment by ql3xHd630** [comment]
hello dirkjanm. i like your azure pentest tools and document very much. 
how to use ROADtools create a context+ derived key?

**Comment by ql3xHd630** [comment]
https://cloud.hacktricks.xyz/pentesting-cloud/azure-security/az-lateral-movement-cloud-on-prem/az-pass-the-certificate
