### ISSUE TITLE
Bloodhound plugin: Connection reset by peer

### ISSUE THREAD

**Issue by m8r1us** [dirkjanm/ROADtools#9]
Hi Dirk-jan

Thank you for the amazing work!!

Quick question regarding the bloodhound plugin: I get the following error while running the bloodhound plugin when I load a massive amount of data:

ConnectionResetError: [Errno 104] Connection reset by peer
self.Error("Failed to write to defunct connection "nebolt.exceptions.ServiceUnavailable: Failed to write to defunct connection Address....)

debug.log:
Bolt connection will be closed because the client did not consume outgoing buffers for 00:15:00.000 which is not expected

The line that leads to that is 191:
```
for memberuser in group.memberUsers:
   add_edge(neosession,memberuser.objectId, 'AzureUser', group.objectId, 'AzureGroup', 'MemberOf')
```
Tried to change the timeout on neo4j side but still running into the same issue. Just wanted to ask if you known this problem already. Otherwise I will let you known when I find a solution.

Thanks

M

**Comment by dirkjanm** [comment]
Not a known issue, but now that you mention it maybe some explicit commits on the session would help prevent this.

**Comment by m8r1us** [comment]
I added / changed line 49 and 50 with:

res = tx.run(...)
res.consume()

It worked - thanks for the hint! :)

**Comment by dirkjanm** [comment]
glad that it worked, will have a look if I can incorporate something like this in the plugin
